import serverKeys from '@/src/lib/serverKeys.json';
import { BUNDLES, LOCALES } from '@/src/lib/i18n';

/**
 * The client half of a two-sided lock.
 *
 * The server ships keys, never sentences — that is what makes a Czech UI a
 * client-only change — and the cost of that split is that nothing connects
 * the Go constants to these bundles. A key added on the server reached a
 * player as SCREAMING_SNAKE and nobody found out until they saw a
 * screenshot; `prompt.pickupMustBeMelded` rendered as "Pickup must be melded
 * 7H" for as long as it existed.
 *
 * `serverKeys.json` is generated by `cd server && go run ./cmd/dump-keys`,
 * and a Go test asserts the committed copy still matches what the server
 * emits. So between the two halves: every key the server can send has words
 * in every locale, and neither side has to know the other's language.
 */

const codesNeedingNoWording = new Set([
  // Refusals a player can never provoke: bad JSON on the socket, an unknown
  // module id, an option the lobby's own controls cannot produce. Wording
  // them would be writing player-facing sentences for programmer errors.
  'BAD_JSON',
  'UNKNOWN_ACTION',
  'UNKNOWN_MODULE',
  'UNKNOWN_VARIATION',
  'UNKNOWN_SUIT',
  'BAD_OPTION',
  'UNKNOWN_OPTION',
  'OPTION_NOT_ALLOWED',
  'NO_RULES',
]);

describe('server key coverage', () => {
  it.each(LOCALES.map((l) => l.id))('%s words every error code the server can send', (locale) => {
    const missing = (serverKeys.errorCodes as string[])
      .filter((code) => !codesNeedingNoWording.has(code))
      .filter((code) => !BUNDLES[locale][`err.${code}`]);
    expect(missing).toEqual([]);
  });

  // Not every key: `humanise` turns an unworded key into readable English by
  // its own shape, and that fallback is what keeps a game added after this
  // build shipped legible on an old client. It is only wrong where it loses
  // something — a key whose meaning lives in its params has nowhere to put
  // them ("Stack", with the number missing), and no fallback can turn
  // `zolik.rules.pickup.obligation` into a rule.
  it.each(LOCALES.map((l) => l.id))('%s words every rule and remedy', (locale) => {
    const missing = (serverKeys.sentenceKeys as string[]).filter((key) => !BUNDLES[locale][key]);
    expect(missing).toEqual([]);
  });

  it.each(LOCALES.map((l) => l.id))('%s words every key that carries a value', (locale) => {
    const missing = (serverKeys.labelKeysWithData as string[]).filter((key) => !BUNDLES[locale][key]);
    expect(missing).toEqual([]);
  });

  it('reports codes the engine declares but never returns', () => {
    // Not a failure — a declared code nothing returns is either an
    // unimplemented rule or a leftover, and only a person can tell which.
    // Asserted so the list cannot grow unnoticed.
    expect(serverKeys.declaredOnly).toEqual(['ADJACENT_WILDS']);
  });
});
